# Generated by Django 4.1.3 on 2022-12-04 12:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0003_alter_therapy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
