# Generated by Django 4.1.3 on 2022-12-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0004_alter_therapy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
