# Generated by Django 4.1.3 on 2022-12-05 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('therapies', '0006_therapy_summary_therapy_therapists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='therapists',
            field=models.ManyToManyField(blank=True, related_name='therapists', to=settings.AUTH_USER_MODEL),
        ),
    ]
