# Generated by Django 4.1.3 on 2022-12-06 15:40

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('therapistCandidate', '0002_alter_therapistcand_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistcand',
            name='cv',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
