# Generated by Django 4.1.3 on 2022-12-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapistCandidate', '0003_therapistcand_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistcand',
            name='motivation',
            field=models.TextField(max_length=5000),
        ),
    ]
