# Generated by Django 4.1.3 on 2022-11-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_therapist',
            field=models.BooleanField(default=False),
        ),
    ]
