# Generated by Django 4.1.3 on 2022-12-06 11:15

import PsychPhil_app.core.validators
import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_managers_appuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='self_summary',
            field=models.TextField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(30), PsychPhil_app.core.validators.validate_only_letters]),
        ),
    ]
