# Generated by Django 4.1.3 on 2022-12-06 12:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_image_profile_self_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='self_summary',
            field=models.TextField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
